name: arithmetic-circuits
version: 0.1.0
synopsis: Arithmetic circuits for zkSNARKs
description: Arithmetic circuits for zkSNARKs
maintainer: Adjoint Inc (info@adjoint.io)
license: MIT
github: adjoint-io/arithmetic-circuits
category: Cryptography

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - NoImplicitPrelude
  - GADTs

dependencies:
  # Base
  - base >= 4.10 && < 5
  - protolude >= 0.2 && < 0.3
  - containers
  - text
  - aeson
  - vector >= 0.12 && < 0.13

  # Algebra
  - poly >= 0.3.2
  - semirings >= 0.5

  # Cryptography
  - bulletproofs >= 1.0
  - elliptic-curve >= 0.3 && < 0.4
  - galois-fft >= 0.1
  - galois-field >= 1 && < 2

  # Misc
  - filepath
  - process-extras
  - wl-pprint-text
  - MonadRandom

extra-source-files:
  - README.md
  - ChangeLog.md

ghc-options:
  - -freverse-errors
  - -O2
  - -Wall

library:
  exposed-modules:
    - Circuit
    - Circuit.Affine
    - Circuit.Arithmetic
    - Circuit.Bulletproofs
    - Circuit.Dot
    - Circuit.Expr
    - Circuit.Lang
    - Fresh
    - QAP
  source-dirs:
    - src

tests:
  circuit-tests:
    main: Main
    dependencies:
      - arithmetic-circuits
      - pairing
      - QuickCheck
      - quickcheck-instances
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck
    source-dirs:
      - test

  readme-test:
    dependencies:
      - arithmetic-circuits
      - base
      - pairing
      - protolude
      - markdown-unlit
    main: README.lhs
    ghc-options: -pgmL markdown-unlit

benchmarks:
  circuit-benchmarks:
    main: Main
    dependencies:
      - criterion
      - pairing
      - arithmetic-circuits
    source-dirs:
      - bench
